# \u041F\u043E\u0434\u043A\u043B\u044E\u0447\u0430\u0435\u043C \u043B\u043E\u043A\u0430\u043B\u044C\u043D\u044B\u0439 \u0444\u0430\u0439\u043B \u0441 \u0441\u0435\u043A\u0440\u0435\u0442\u0430\u043C\u0438, \u0435\u0441\u043B\u0438 \u043E\u043D \u0435\u0441\u0442\u044C (\u0441\u043C. .env.properties.example).
# \u0420\u0435\u0430\u043B\u044C\u043D\u044B\u0435 \u0437\u043D\u0430\u0447\u0435\u043D\u0438\u044F \u043F\u0435\u0440\u0435\u043C\u0435\u043D\u043D\u044B\u0445 \u043E\u043A\u0440\u0443\u0436\u0435\u043D\u0438\u044F (DB_PASSWORD, TELEGRAM_BOT_TOKEN \u0438 \u0442.\u0434.)
# \u0432\u0441\u0435\u0433\u0434\u0430 \u0438\u043C\u0435\u044E\u0442 \u043F\u0440\u0438\u043E\u0440\u0438\u0442\u0435\u0442 \u043D\u0430\u0434 \u044D\u0442\u0438\u043C \u0444\u0430\u0439\u043B\u043E\u043C, \u043F\u043E\u044D\u0442\u043E\u043C\u0443 \u043D\u0430 \u0441\u0435\u0440\u0432\u0435\u0440\u0435/\u043F\u0440\u043E\u0434\u0435 \u043E\u043D \u043D\u0435 \u043D\u0443\u0436\u0435\u043D.
spring.config.import=optional:file:./.env.properties

spring.application.name=DemoBotTelega

# Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/notify_machine}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# Telegram Bot
telegram.bot.username=${TELEGRAM_BOT_USERNAME}
telegram.bot.token=${TELEGRAM_BOT_TOKEN}

# Kafka
spring.kafka.properties.allow.auto.create.topics=true
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Kafka Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

# Kafka Consumer
spring.kafka.consumer.group-id=machine-bot-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
