spring.application.name=DemoBotTelega

spring.datasource.url=jdbc:postgresql://localhost:5432/notify_machine
spring.datasource.username=postgres
spring.datasource.password=Glasner@08

spring.jpa.hibernate.ddl-auto=update

telegram.bot.username=TestNotifyTrk
telegram.bot.token=8848305600:AAHKMC0Ph0SQk-SCnPtYYpvjshkVc6aFJM4
