spring.application.name=DemoBotTelega

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/notify_machine
spring.datasource.username=postgres
spring.datasource.password=Glasner@08
spring.jpa.hibernate.ddl-auto=update

# Telegram Bot
telegram.bot.username=TestNotifyTrk
telegram.bot.token=8848305600:AAHKMC0Ph0SQk-SCnPtYYpvjshkVc6aFJM4

# Kafka
spring.kafka.properties.allow.auto.create.topics=true
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Kafka Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

# Kafka Consumer
spring.kafka.consumer.group-id=machine-bot-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=h1llapple16@gmail.com
spring.mail.password=loalezvzpjagtsty
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

# ????????? ????-???????????? Kafka (Consumer/Producer ????????? ???????)
