spring.application.name=DemoBotTelega

spring.datasource.url=jdbc:postgresql://localhost:5432/notify_machine
spring.datasource.username=postgres
spring.datasource.password=Glasner@08

spring.jpa.hibernate.ddl-auto=update

telegram.bot.username=TestNotifyTrk
telegram.bot.token=8848305600:AAHKMC0Ph0SQk-SCnPtYYpvjshkVc6aFJM4

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.properties.allow.auto.create.topics=true

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

# Consumer
spring.kafka.consumer.group-id=machine-bot-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer